/* GStreamer
 * Copyright (C) <2006> Philippe Khalaf <burger@speedy.org> 
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

/* RFC 3551 */
gchar default_pt_table[] =
    "application/x-rtp, "
      "encoding-name = (string) \"PCMU\","
      "media = (string) \"audio\","
      "payload = (int) 0,"
      "clock-rate = (int) 8000" ";"
    /*
    "application/x-rtp, "
      "encoding-name = (string) \"1016\","
      "media = (string) \"audio\","
      "payload = (int) 1,"
      "clock-rate = (int) 8000"";"
    "application/x-rtp, "
      "encoding-name = (string) \"G721\","
      "media = (string) \"audio\","
      "payload = (int) 2,"
      "clock-rate = (int) 8000" ";"
      */
    "application/x-rtp, "
      "encoding-name = (string) \"GSM\","
      "media = (string) \"audio\","
      "payload = (int) 3,"
      "clock-rate = (int) 8000" ";"
    "application/x-rtp, "
      "encoding-name = (string) \"G723\","
      "media = (string) \"audio\","
      "payload = (int) 4,"
      "clock-rate = (int) 8000" ";"
    "application/x-rtp, "
      "encoding-name = (string) \"DVI4\","
      "media = (string) \"audio\","
      "payload = (int) 5,"
      "clock-rate = (int) 8000" ";"
    "application/x-rtp, "
      "encoding-name = (string) \"DVI4\","
      "media = (string) \"audio\","
      "payload = (int) 6,"
      "clock-rate = (int) 16000" ";"
    "application/x-rtp, "
      "encoding-name = (string) \"LPC\","
      "media = (string) \"audio\","
      "payload = (int) 7,"
      "clock-rate = (int) 8000" ";"
    "application/x-rtp, "
      "encoding-name = (string) \"PCMA\","
      "media = (string) \"audio\","
      "payload = (int) 8,"
      "clock-rate = (int) 8000" ";"
    "application/x-rtp, "
      "encoding-name = (string) \"G722\","
      "media = (string) \"audio\","
      "payload = (int) 9,"
      "clock-rate = (int) 8000" ";"
    "application/x-rtp, "
      "encoding-name = (string) \"L16\","
      "media = (string) \"audio\","
      "payload = (int) 10,"
      "clock-rate = (int) 44100" ";"
    "application/x-rtp, "
      "encoding-name = (string) \"L16\","
      "media = (string) \"audio\","
      "payload = (int) 11,"
      "clock-rate = (int) 44100" ";"
    "application/x-rtp, "
      "encoding-name = (string) \"QCELP\","
      "media = (string) \"audio\","
      "payload = (int) 12,"
      "clock-rate = (int) 44100" ";"
    "application/x-rtp, "
      "encoding-name = (string) \"CN\","
      "media = (string) \"audio\","
      "payload = (int) 13,"
      "clock-rate = (int) 44100" ";"
    "application/x-rtp, "
      "encoding-name = (string) \"MPA\","
      "media = (string) \"audio\","
      "payload = (int) 14,"
      "clock-rate = (int) 90000" ";"
    "application/x-rtp, "
      "encoding-name = (string) \"G728\","
      "media = (string) \"audio\","
      "payload = (int) 15,"
      "clock-rate = (int) 8000" ";"
    "application/x-rtp, "
      "encoding-name = (string) \"DVI4\","
      "media = (string) \"audio\","
      "payload = (int) 16,"
      "clock-rate = (int) 11025" ";"
    "application/x-rtp, "
      "encoding-name = (string) \"DVI4\","
      "media = (string) \"audio\","
      "payload = (int) 17,"
      "clock-rate = (int) 22050" ";"
    "application/x-rtp, "
      "encoding-name = (string) \"CelB\","
      "media = (string) \"video\","
      "payload = (int) 25,"
      "clock-rate = (int) 90000" ";"
    "application/x-rtp, "
      "encoding-name = (string) \"JPEG\","
      "media = (string) \"video\","
      "payload = (int) 26,"
      "clock-rate = (int) 90000" ";"
    "application/x-rtp, "
      "encoding-name = (string) \"nv\","
      "media = (string) \"video\","
      "payload = (int) 28,"
      "clock-rate = (int) 90000" ";"
    "application/x-rtp, "
      "encoding-name = (string) \"H261\","
      "media = (string) \"video\","
      "payload = (int) 31,"
      "clock-rate = (int) 90000" ";"
    "application/x-rtp, "
      "encoding-name = (string) \"MPV\","
      "media = (string) \"video\","
      "payload = (int) 32,"
      "clock-rate = (int) 90000" ";"
    "application/x-rtp, "
      "encoding-name = (string) \"MP2T\","
      "media = (string) \"audiovideo\","
      "payload = (int) 33,"
      "clock-rate = (int) 90000" ";"
    "application/x-rtp, "
      "encoding-name = (string) \"H263\","
      "media = (string) \"video\","
      "payload = (int) 34,"
      "clock-rate = (int) 90000";
