echo @echo off > "%SHORTCUTFILE%"
echo REM ------------ >> "%SHORTCUTFILE%"
echo REM Run Examples >> "%SHORTCUTFILE%"
echo REM ------------ >> "%SHORTCUTFILE%"
echo if not "%%CommonProgramFiles(x86)%%" == "" goto 64bit >> "%SHORTCUTFILE%"
echo if "%%CommonProgramFiles(x86)%%" == "" goto 32bit >> "%SHORTCUTFILE%"
echo :64bit >> "%SHORTCUTFILE%"
echo set COMMONFILES=%%CommonProgramFiles(x86)%% >> "%SHORTCUTFILE%"
echo goto End >> "%SHORTCUTFILE%"
echo :32bit >> "%SHORTCUTFILE%"
echo set COMMONFILES=%%CommonProgramFiles%% >> "%SHORTCUTFILE%"
echo goto End >> "%SHORTCUTFILE%"
echo :End >> "%SHORTCUTFILE%"
echo start "%%COMMONFILES%%\microsoft shared\MSEnv\vslauncher.exe" "%%~dp0Examples\%SOLUTIONFILE%" >> "%SHORTCUTFILE%"